version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT2}"
    networks:
      - common-network

networks:
  common-network:
    external:
      name: common-network
