export const professeursData = [
  {
    id: 0,
    titleProf: "Julien Beaudiment",
    textProf:"Assistant teacher at the Conservatoire National Supérieur de Musique de Lyon and artistic deputy at the Haute Ecole de Musique de Lausanne in Switzerland ",
      imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Julien-Beaudiment-Flute-Masterclass-1.jpg",
      detailProf:"Renown flautist Julien Beaudiment brilliantly represents the French flute school. Born in 1978, he crossed the Channel when he was 18 years old, to study at the Guidhall School of Music in London with Paul Edmund-Davies and Averill Williams. He stayed there two years, before finishing his studies at the “Conservatoire National Superieur de Musique de Paris” with Sophie Cherrier, assisted by Vincent Lucas and Michel Moragués for Chamber Music. He successfully obtained the flute and chamber music awards. His studies enabled him to rub shoulders with other great professors, such as Vicens Prats, Maxence Larrieu, Jacques Zoon, Benoît Fromanger, Ramson Wilson, Joshua Smith.",
      instrumentCategory: "Flute",
    },
    { id: 1,
      titleProf: "Sophie Cherrier",
      textProf:
      "Professor at CNSMD",
      imageProf : " https://www.salineacademy.com/wp-content/uploads/2023/06/Sophie-Cherrier-Flute-Masterclass-1.jpg",
      instrumentCategory: "Flute",
      detailProf : "Sophie Cherrier studied at the Conservatoire National de Région de Nancy and then at the Conservatoire National Supérieur de Musique de Paris, where she graduated with highest honors in flute (under the tutelage of Alain Marion) and chamber music (under the tutelage of Christian Lardé). She joined the Ensemble intercontemporain in 1979. She has performed in the premieres of numerous works, including Mémoriale by Pierre Boulez, Esprit rude/Esprit doux by Elliott Carter (Deutsche Grammophon recording), and Chu Ky Vby Ton-Thât Tiêt."
    },
    { id : 2,
      titleProf: "Lee Soyoung ",
      textProf:
      "Professor at Kunkook University, Seoul Arts center and Seoul Hight School of Arts",
      imageProf : " https://www.salineacademy.com/wp-content/uploads/2023/06/Soyoung-Lee-Flute-Masterclass-1.jpg",
      instrumentCategory: "flute",
      detailProf :"After graduating from the Seoul High School of Arts, Soyoung Lee continued her studies in the Oberlin College and Yale University. A student of Michel Debost and Ransom Wilson, she has won many competitions in America. Lee played as principal flute of the Bucheon Philharmonic Orchestra from 1992 until 2011, one of the leading orchestras in Korea. Soyoung Lee has given many concerts in Seoul. She has also played with the Ensemble of Tokyo as a guest principal flute several times. Lee teaches at Kunkook University, Seoul Arts Center and Seoul High school of arts.",
  },
  { id : 3,
    titleProf: "Stépahine-Marie Degand ",
    textProf:
    "Professor at the CNSMD of Paris",
    imageProf : " https://www.salineacademy.com/wp-content/uploads/2023/06/Stephanie-Marie-Degand-Violin-masterclass-1.jpg",
    instrumentCategory: "Violon",
    detailProf:"Stéphanie-Marie Degand is nowadays one of the rare performers able to master the techniques and codes of a repertoire ranging from the 17th century to contemporary creation. Trained in Caen by Jean-Walter Audoli and Emmanuelle Haïm, she entered the Conservatoire National Supérieur de Musique et de Danse de Paris in Jacques Ghestem’s class and immediately affirmed her ambition to decompartmentalise repertoires, benefiting from the teaching of masters such as Jacques Rouvier, Alain Meunier, Pierre-Laurent Aimard, but also William Christie, Christophe Rousset, Patrick Bismuth and Christophe Coin. She obtained 4 first prizes and followed the advanced violin course, before embarking on an atypical career. A confirmed soloist, passionate chamber musician, committed solo violinist, conductor and teacher, her artistic approach has been hailed by numerous awards: Grand Prix Adami 95, 2nd Grand Prix of the Ferras-Barbizet Competition 97, Classical Revelation at Midem 98, Natexis Laureate 99, Sacem Prize 2002, Revelation “Instrumental Soloist” at the Victoires de la Musique 2005. She has performed in the most prestigious concert halls under the baton of Emmanuel Krivine, François-Xavier Roth, Jérémie Rhorer, Laurence Equilbey and in chamber music with Marie-Josèphe Jude, François-Frédéric Guy, Christie Julien, Violaine Cochard, Christophe Rousset, Emmanuelle Bertrand, Marc Coppey, Miguel Da Silva…"
},
{ id : 4,
  titleProf: "Jean-Marc Phillips-Varjabédian",
  textProf:
  "Professor at the CNSMD of Paris",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jean-Marc-Phillips-Varjabedian-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :"Jean-Marc Phillips-Varjabédian began studying the violin at age 5. He was admitted to Conservatoire National Supérieur de Musique de Paris at age 13. He received a First Prize in chamber music in 1984 and a violin First Prize in 1985. After studying under the direction of Gérard Poulet and Jean-Claude Bernède, Jean-Marc Phillips-Varjabédian moved to Cremona, Italy, to work under the direction of Salvatore Accardo. He then spent one year at the Julliard School in New York to study with Dorothy Delay. He has won several prizes in international violin competitions (Carl Flesch, Zino Francescatti, Lipizer, Palm Beach)."
},
{ id : 5,
  titleProf: "Jonas Vitaud",
  textProf:
  "Professor at Paris Conversation since 2013, and currently assistant professor in Marie-Josephe Jude's piano Class",
  imageProf : " https://www.salineacademy.com/wp-content/uploads/2023/06/Jonas-Vitaud-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :"Jonas Vitaud was born in 1980, and began studying the piano at the age of six and the organ at eleven. A student of Brigitte Engerer, Jean Koerner and Christian Ivaldi, he obtained four premiers prix (piano, chamber music, piano accompaniment, harmony) at the Conservatoire National Supérieur de Musique de Paris, and went on to win prizes at several international competitions (Lyon, the ARD-Musikwetteberb in Munich, Trieste, the International Beethoven Piano Competition in Vienna) as both soloist and chamber musician. Jonas Vitaud continues to give performances in recital and also with orchestras. He appears regularly at numerous famous festivals in Europe and throughout the world as la Roque d’Anthéron, La Folle Journée in Nantes, Tokyo, Yekaterinburg and Warsaw the Festival de La Chaise-Dieu, the Goslar festival, the Richard Strauss Festival at Garmisch-Partenkirchen in Germany, Autunno Musicale at Caserta in Italy, iDans in Istanbul, the Dubrovnik Summer Festival, and French May in Hong Kong, and has also performed at the Phillips Collection in Washington."
},
{ id : 6,
  titleProf: "Johand Schmit ",
  textProf:
  "Professor at the Royal Conservatory of Brussels and at Qingdao University in China and Senzoku Gakuen University in Japan.",
  imageProf : " https://www.salineacademy.com/wp-content/uploads/2023/06/Johan-Schmidt-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :"Johan Schmidt has conquered the international piano scene both through his personality and his musically profound and technically masterful expression. Johan Schmidt is invited as a soloist to the most renowned venues worldwide, such as the Palais des Beaux-Arts in Brussels, the Théâtre du Châtelet and Théâtre de la Ville in Paris, the Rachmaninov Hall in Moscow, the Herod Atticus Theatre in Athens, the Concertgebouw in Amsterdam, the Gasteig in Munich, the Schaubühnenhaus in Berlin, the Tel Aviv Museum, the Suntory and Casals Halls in Tokyo, the Symphony Hall in Osaka, the Shanghai Oriental Art Center, the Grand Theatre in Qingdao, the Dalian Theatre…"
},
{ id : 7,
  titleProf: "Akkiko Ebi",
  textProf:
  "She serves on the juries of international competitions around the world",
  imageProf : " https://www.salineacademy.com/wp-content/uploads/2023/06/Akkiko-Ebi-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf : "Akiko EBI is a world‐class pianist. Ebi developed her career after winning the 41st Music Competition of Japan in her freshman year at Tokyo National University of Fine Arts and Music. After graduating at the top of her class from the Paris Conservatoire, she studied in the graduate school of the Conservatoire as well.EBI was Grand Prix winner of the Marguerite Long‐Jacques Thibaud Competition, where she was also awarded four special prizes by A. Rubinstein and others. She also won the 5th prize of the International Chopin Piano Competition in 1980. Akiko EBI serves on the juries of international competitions around the world. She was chair of the jury of the 8th and 9th Hamamatsu International Piano Competitions. She served on the juries of the Marguerite Long‐ Jacques Thibaud Competition and the 17th International Chopin Piano Competitions in Warsaw."
},
{ id : 8,
  titleProf: "Marie-Pierre Langlamet",
imageProf:
  "https://www.salineacademy.com/wp-content/uploads/2023/06/Marie-Pierre-Langlamer-Harp-masterclass-1.jpg",
  textProf : " Professor at the Herbet von Karajan Academy ince 1995, and since April 2029 also at the Universitat der Kunste in Berlin",
  detailProf:" ",
  instrumentCategory: "Harpe",
},
{ id : 9,
  titleProf: "Denis Servin",
  imageProf :"https://www.salineacademy.com/wp-content/uploads/2023/06/Denis-Severin-Cello-Masterclass-1.jpg",
  textProf: "Professor of cello at the Genvea University of Music and the Bern University of Arts ",
  instrumentCategory: "Cello",
  detailProf : "A coveted guest professor, Denis Severin also teaches master classes and leads orchestra projects at the Centro superior de musical Katarina Gurska (Madrid, Spain), the Jāzeps Vītols Academy of Music (Riga, Latvia), the Central Conservatory of Music (Beijing, China), Franz Liszt Academy of Music (Budapest, Hungary) and the National University of Arts (Kharkov, Ukraine).egularly gives summer master-classes in Germany, France, Poland, Russia, Georgia and Brazil.Denis Severin is Prize Winner of ECHO KLASSIK (2015) and GRAMMY AWARDS (2007), laureate of several international competitions in Greece, Italy and Spain."
},
{ id : 10,
  titleProf: "Pierre Génisson",
  imageProf:
  "https://www.salineacademy.com/wp-content/uploads/2023/06/Pierre-Genisson-Clarinet-Masterclass-1.jpg",
  textProf : " He won the 1st Prize and the Audience Prize at the Jacques Lancelot International Competition In Tokyo",
  instrumentCategory: "Clarinet",
  detailProf:" Born in 1986 in Marseille, Pierre Génisson is one of the best representatives of the French wind school. Winner of the prestigious Carl Nielsen International Competition, he won the 1st Prize and the Audience Prize at the Jacques Lancelot. International Competition in Tokyo. His recordings published for Aparté records – Harmonia mundi have been widely awarded by international critics (Diapason d’or, Choc of the year by Classica, ffff by Télérama, “CD of the week” by the Sunday Times, Gramophone, Clef d’Or by Resmusica …) Pierre Genisson trained at the Conservatoire National Supérieur de Musique de Paris with Michel Arrignon for the clarinet, Claire Désert, Amy Flammer and Jean Sulem for chamber music. After two unanimous ‘First prize’ in these two disciplines, he went to perfect his skills at the University of Southern California Los Angeles with Pr. Yehuda Gilad where he obtained an‘Artist Diploma’. "
},
{ id : 11,
  titleProf: "Philippe Graffin",
  textProf:" He teaches at the Royal Conservatory of Brussels and tje CNSM of Paris",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Philippe-Graffin-Violin-Masterclass-1.jpg ",
  instrumentCategory: "Violon",
  detailProf :"A student of Josef Gingold in the United States, himself a student of Ysaye and Philippe Hirschorn, Philippe Graffin won the Fritz Kreisler Competition in Austria, where Lord Menuhin discovered him and invited him to record his first CD under his direction. Since then, he has shared the stage with some of the most emblematic artists of our time, such as Mtislav Rostropovich, Sir Roger Norrington, Ernest Bour, Sir Yehudi Menuhin, Stephen Kovacevich and the Romanian conductor Sergio Comissiona. Many composers have written and dedicated their works to Philippe Graffin such as the Russian composer Rodion Shchedrin with his “concerto parlando”, David Matthews and his concerto n.2, the Lithuanian composer Vytautas Barkauskas, “jeux” for violin and orchestra, as well as his double concerto with the violist Nobuko Imai. Philippe has also premiered Yves Prin’s concerto and numerous works written for him by Philippe Hersant. "
},
{ id : 12,
  titleProf: "Gérard Caussé",
  textProf:"International Soloist",
  detailProf :" Gérard Caussé has been exploring all the territories of the viola’s voice for many years: as a soloist, chamber musician, conductor and teacher, he has recently developed a passion, with Laurent Terzieff, for the dialogue between poetry and music, as evidenced by the Erato recording of Bach’s Cello Suites, transcribed for the viola, interwoven with Rilke’s poetry. Caussé is an international soloist under the baton of the greatest conductors, with the most prestigious ensembles; defender of the contemporary repertoire, has been a solo viola, since the foundation of the Ensemble Intercontemporain by Pierre Boulez; and is a faithful and sought-after chamber musician as well as a regular partner of the greatests: Gidon Kremer, Mischa Maisky, Michel Portal, Renaud Capuçon, Franck Braley, Nicholas Angelich… A renowned teacher, from the Escuela Reina Sofia in Madrid to the Conservatoire Supérieur de Paris, Cussé is also a conductor and musical director for the Toulouse Chamber Orchestra and the Caja Duero Foundation Camerata in Salamanca. As a generous intermediary with the younger generation, Gérard Caussé embodies all the facets of the life of an outstanding viola player, having developed them throughout his career",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Gerard-Causse-Viola-Masterclass-1.jpg ",
  instrumentCategory: "Violon",
},
{ id : 13,
  titleProf: "Jean-Frédéric Neuburger",
  textProf :"International Solist and concert artist",
  detailProf:"Born in Paris in 1986, Jean-Frédéric Neuburger received an intense and varied musical education in piano, composition and organ before joining the Conservatoire National Supérieur de Musique et de Danse de Paris at the age of thirteen. On graduating from the CNSM with Five ‘Premier Prix’ he went on to study composition with Michael Jarrell and Pascal Dusapin in Geneva.He has, since then established himself as one of the most gifted musicians of his generation, both as a composer and an interpreter known for the extreme variety of his repertoire.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jean-Frederic-Neuburger-Piano-Masterclass-1.jpg ",
  instrumentCategory: "Piano",
},
{ id : 14,
  titleProf: "Dmitri Alexeev",
  textProf :" Professor at the Royal College of Music of London",
  detailProfProf:"Russian pianist Dmitri Alexeev is one of the world’s most highly regarded artists. His critically acclaimed recitals on the world’s leading concert stages and concerto appearances with the most prestigious orchestras have secured his position as one of “the most remarkable pianists of the day” (Daily Telegraph)",
  imageProf : " https://www.salineacademy.com/wp-content/uploads/2023/06/Dmitri-Alexeev-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 15,
  titleProf: "Nelson Goerner",
  textProf:"Nelson Goerner is one of today’s greatest classical pianists. He is heralded for his performances of the highest art and poetry, while at the same time possessing exhilarating and masterful conviction.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Nelson-Goerner-Piano-Masterclass-1.jpg ",
  instrumentCategory: "Piano",
  detailProf :" Nelson Goerner is one of today’s greatest classical pianists. He is heralded for his performances of the highest art and poetry, while at the same time possessing exhilarating and masterful conviction. In the 2019-20 season Nelson Goerner will give recitals on some of the world’s most important stages, including Paris’s Théâtre des Champs-Elysées, London’s Wigmore Hall, Brussels’ BOZAR and Toulouse’s Cloitre des Jacobins, and give concerto appearances with La Monnaie Symphony Orchestra and Alain Altinoglu, the Orchestre Philharmonique de Radio France and Myung-Whun Chung, and the Luzerner Sinfonieorchester under Lawrence Foster.Nelson Goerner has performed with many of today’s major orchestras including the Philharmonia Orchestra, Orchestre de Paris, London Philharmonic Orchestra, Deutsche Kammerphilharmonie, Hallé Orchestra, Sinfonia Varsovia and NHK Symphony Orchestra, and with several of today’s leading conductors such as Vladimir Ashkenazy, Philippe Herreweghe, Neeme Järvi, Sir Mark Elder, Paavo Järvi, Vassily Sinaisky, Jonathan Nott, Fabio Luisi and Esa-Pekka Salonen. His festival appearances include today’s most prestigious engagements, including Salzburg Festival, La Roque d’Anthéron, La Grange de Meslay, Edinburgh International Festival, Festival de Verbier, La Folle Journée (Nantes and Tokyo), Schleswig-Holstein, Warsaw’s ‘Chopin and his Europe’ and the BBC Proms."
},
{ id : 16,
  titleProf: "Ning Feng",
  textProf:"Ning Feng is recognised internationally as an artist of great lyricism, innate musicality and stunning virtuosity. He performs across the globe with major orchestras and conductors, and in recital and chamber concerts in some of the most important international series and festivals.",
  imageProf : " https://www.salineacademy.com/wp-content/uploads/2023/06/Ning-Feng-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :" Ning Feng is recognised internationally as an artist of great lyricism, innate musicality and stunning virtuosity. He performs across the globe with major orchestras and conductors, and in recital and chamber concerts in some of the most important international series and festivals.In 2019 the Washington Post described him as “a wonderful player with a creamy, easy tone and an emotional honesty” and BBC Music Magazine said of a recent recording “His silvery tonal purity, immaculate intonation and gently beguiling musicality have a way of making most other players sound decidedly effortful by comparison.”Ning Feng has toured Europe, Asia and Australia with the Hong Kong Philharmonic Orchestra/ van Zweden, he has toured China with many orchestras including the Budapest Festival Orchestra/ Iván Fischer, with whom he has also performed several times in Budapest, with the Berlin Konzerthaus Orchester/ Lawrence Foster, and with the Royal Liverpool Philharmonic Orchestra with whom he has also worked many times."
},
{ id : 17,
  titleProf: "Tedi Papavram",
  textProf:"Professor at the Haute École de Musique in Geneva. He won several important international prizes in the 1990s.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Tedi-Papavrami-Violin-Masterclass-1.jpg ",
  instrumentCategory: "Violon",
  detailProf : "Born in Albania, Tedi Papavrami was introduced to the violin at age five by his father, a brilliant teacher with many years of pedagogical experience. Tedi progressed rapidly, and within three years he was performing at Sarasate’s Airs Bohémiens with the Tirana Philharmonic Orchestra. At the age of eleven, he tackled Paganini’s Concerto No. 1 with the Emile Sauret’s fearsome and challenging cadenza.In 1982, French flautist Alain Marion, who had come to give a concert in Tirana, heard the child prodigy play – and promptly arranged for him to come to Paris with a bursary from the French government. Tedi went on to study with Pierre Amoyal at the Conservatoire National Supérieur de Musique. Moreover, he appeared on popular television programs and gave many concerts at that time."
},
{ id : 18,
  titleProf: "Sivia Careddu",
  textProf:"Professor at the École Normale de Musique Alfred Cortot in Paris. Professor at the Scuola di Musica di Fiesole, in Italy.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Silvia-Careddu-Flute-Masterclass-1.jpg",
  instrumentCategory: "Flute",
  detailProf : "Silvia Careddu was born in Cagliari, Italy, and studied at the Conservatoire de Musique et de Danse de Paris, where she graduated with distinctions. She made an auspicious start to her career by winning unanimously the First Prize and the Audience Prize at the 56th Concours International de Genève. Following the award, Lorin Maazel invited Careddu to be the solo flute of his newly founded Filarmonica Arturo Toscanini. She later joined the Konzerthausorchester Berlin, the Wiener Symphoniker and the Wiener Philharmoniker-Wiener Staatsoper, as principal flute. In 2012, she became artistic partner of the Kammerakademie Potsdam, winner of the Echo-Preis 2015 for the category Best German Orchestra. As guest principal flute, Silvia plays with the Mahler Chamber Orchestra, the Bavarian Radio Symphony Orchestra, Philharmonia Orchestra, the Chamber Orchestra of Europe, Budapest Festival Orchestra, Maggio Musicale Fiorentino, and the Sinfonia Grange au Lac. Silvia is a founding member of the Alban Berg Ensemble Wien, a chamber music group made up of virtuoso instrumentalists."
},
{ id : 19,
  titleProf: "Sharon Kam",
  textProf:"One of the world's leading clarinet soloists, she has worked with renowned orchestras.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Sharon-Kam-Clarinet-Masterclass-1.jpg",
  instrumentCategory: "Flute",
  detailProf :"Sharon Kam is one of the world’s leading clarinet soloists, and has been working with renowned orchestras in the United States, Europe, and Japan for over 20 years. In particular, Mozart’s clarinet masterpieces have been an object of artistic focus for Ms. Kam since the beginning of her career. At the age of sixteen, she performed Mozart’s Clarinet Concerto in her orchestral debut with the Israel Philharmonic Orchestra and Zubin Mehta.Shortly afterwards, she performed the Clarinet Quintet with the Guarneri String Quartet in Carnegie Hall, New York. As part of Mozart’s 250th birthday celebrations at the National Theatre in Prague, her interpretation of the Mozart concerto was televised live in 33 countries and is currently available on DVD. In the same year, she achieved her longtime dream of recording the Concerto and the Clarinet Quintet playing the basset clarinet."
},
{ id : 20,
  titleProf: "Mia Cooper",
  textProf:"Professor of Violin at the Royal Irish Academy of Music. She was principal first violin of the Royal Philharmonic Orchestra for five years.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Mia-Cooper-Violin-Masterclass-1.jpg",
  instrumentCategory: "Flute",
  detailProf :"Mia Cooper studied at the Royal Northern College of Music with Yossi Zivoni and Chamber Music at the Paris Conservatoire with Michel Strauss. On graduating, Mia was principal first violin of the Royal Philharmonic Orchestra for five years, and played with many of London’s chamber orchestras and ensembles, including the Fibonacci Sequence, Barbican Trio, Brodsky Quartet, Chamber Orchestra of Europe and Academy of St Martin-in-the-Fields.Mia was appointed leader of the RTÉ Concert Orchestra in 2006, and in the same year took up a position as Professor of Violin at the Royal Irish Academy of Music. Mia has given masterclasses in the UK, Spain and Lithuania through Erasmus exchanges.Mia is a highly sought out guest leader and as such has worked with the City of Birmingham Symphony Orchestra, BBC National Orchestra of Wales, Royal Scottish National Orchestra, Philharmonia and Royal Philharmonic Orchestra.Mia’s love of chamber music grew at an early age, and as a founding member of the Esposito quartet has given many radio broadcast concert tours of Ireland. Mia has also recorded a wide variety of chamber music, including the violin sonatas of Michele Esposito, and recordings for Naxos and Chandos as a guest of the Gould Piano Trio."
},
{ id : 21,
  titleProf: "Mary Brennan",
  textProf:"Professor at Vocal Studies Faculty of the Royal Irish Academy of Music since 2007",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Mary-Brennan-Voice-Masterclass-1.jpg",
  instrumentCategory: "Voice",
  detailProf :"Mary Brennan is a graduate of the Royal Northern College of Music. She was a lecturer at DIT Conservatory of Music and Drama 1987-2007. She has been a teacher in the Vocal Studies Faculty of the Royal Irish Academy of Music since 2007, teaching for the most part Bachelor, Masters and Doctorate Students. Mary also delivers French Song Classes with 3rd and 4th Year Undergraduates, and Recital Artist students. Mary was a Senior Lecturer at the Royal Northern College of Music in Manchester from 2002-2007 and Visiting Professor at the Opera Studio in Ghent from 1998-2003. She was a visiting lecturer for Senior and Master students at the School of Fine Arts of the University of Connecticut in 2013.Many of Mary’s past students at the RIAM are now enjoying successful performing careers, including Naomi O’Connell, Rachel Kelly, Claudia Boyle, Dean Power, Gavan Ring, Sarah Brady and Padraic Rowan. Of her emerging professional students, in recent years three of her class have been awarded the prestigious Royal Dublin Society Bursary of €15,000, an award which is also competed for amongst Keyboard, Strings, Wind and Brass players."
},
{ id : 22,
  titleProf: "Jacques Mauger",
  textProf:"Professor at the Haute école de musique de Genève. International soloist and concert artist.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jacques-Mauger-Trombone-Masterclass-1.jpg",
  instrumentCategory: "Trombone",
  detailProf :"Jacques Mauger was born in Normandy, France, and studied the trombone at the Conservatoire National Supérieur de Musique de Paris. A prize-winner at international competitions in Markneukirchen and Toulon, he started his professional career as First Trombone with the Nice Philarmonic Orchestra, followed by a position as a solo trombonist for the Paris Opera Orchestra. Since 1990, he has been a concert artist, appearing as a soloist with ensembles, symphony orchestras, and brass and concert bands. In addition, he has made TV appearances on ZDF, GLOBO, RAI and MUZZIK in France, and many international composers have composed original works or made special arrangements for him. He has recorded over 30 CDs featuring his solo works. Jacques Mauger teaches at the Conservatoire à Rayonnement Régional in Paris and at the HEMU in Switzerland. Moreover, he is a guest professor at the Senzoku Gaquen University of Tokyo, Japan. He frequently gives masterclass in numerous countries: France, UK, Japan, Korea, China, Spain, Germany, Switzerland, Holland, the United States, and South America. In 2007, his collection of studies for trombone (in collaboration with Jean Michel Defaye) were published. He also developed the new AC440 trombone model in Antoine Courtois Paris brass factory. A true Ambassador of the French school and its repertoire, he regularly presents masterclasses all over the world to cultivate the careers of future soloists. Jacques Mauger is the new president of the “Association des Trombonistes Français” and president of the International Trombone Association since 2020."
},
{ id : 23,
  titleProf: "Isabel Charisius",
  textProf:"Member of the Alban Berg Quartet from 2005 to 2008. Teacher at the European Centre for Chamber Music - ProQuartet.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Isabel-Charisius-Chamber-music-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf:"Isabel Charisius is one of the finest violists and chamber musicians of her generation. As a member of the legendary Alban Berg Quartet, and a regular soloist with leading orchestras, Charisius has appeared regularly at the most prestigious venues in Europe, the Americas, and Asia.She enjoys working in projects with distinguished string quartets, various ensembles and many renowned soloists in international venues. She is frequently invited as a jury member to prestigious international competitions.For many years, Charisius has been dedicated to developing the journeys of new generations of musicians. She is an internationally recognized teacher of viola and chamber music. Her prolific teaching activity at the Universities of Cologne and Lucerne as well as a wide range of masterclasses at some of the most prestigious institutions, has produced a large community of alumni. Her students can be found among the winners of international competitions, and many of them are members of the world’s finest ensembles and orchestras.Isabel Charisius plays the extraordinary viola «ABQ» by Laurentius Storioni (1780)."
},
{ id : 24,
  titleProf: "Dénes Várjon",
  textProf:"He won first prize at the Piano Competition of Hungarian Radio, at the Leó Weiner Chamber Music Competition and at the Géza Anda Competition.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Denes-Varjon-Piano-Masterclass-1.jpg-1.jpg",
  instrumentCategory: "Piano",
  detailProf : "Widely considered as one of the greatest chamber musicians, he works regularly with pre-eminent partners such as Steven Isserlis, Tabea Zimmermann, Kim Kashkashian, Jörg Widmann, Leonidas Kavakos, András Schiff , Heinz Holliger, Miklós Perényi, and Joshua Bell. As a soloist, he is a welcome guest at major concert series, from New York’s Carnegie Hall to Vienna’s Konzerthaus and London’s Wigmore Hall. He is frequently invited to work with many of the world’s leading symphony orchestras (Budapest Festival Orchestra, Tonhalle Orchestra, Berlin Radio Symphony Orchestra, St. Petersburg Philharmonic Orchestra, Chamber Orchestra of Europe, Russian National Orchestra, Kremerata Baltica, Academy of St. Martin in the Fields)."
},
{ id : 25,
  titleProf: "Claire-Marie Le Guay",
  textProf:"Professor at the CNSMD of Paris.First prize winner at ARD Competition in Munich (1994).",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Claire-Marie-Le-Guay-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf : "A regular presence on concert platforms around the world, a prizewinner at numerous international competitions, at the Victoires de la Musique and of the Banque Populaire Foundation, Claire-Marie Le Guay is also noted for her recordings of Liszt, Schumann, Haydn, Mozart and Dutilleux, which have all been acclaimed by the press (‘Maestro’ of Pianiste magazine, Choc de Classica, Diapason, Gramophone), as was her recent Bach disc released on Mirare in 2015. She is a highly sought-after solo pianist and performs with the most prestigious conductors and orchestras, including the Orchestre de Paris, the Symphonieorchester des Bayerischen Rundfunks, the New Japan Philharmonic and the London Philharmonic Orchestra. She has been invited to tour the United States by Daniel Barenboim and to play with Gidon Kremer and the Kremerata Baltica, and also appears regularly under the direction of Louis Langrée. Claire-Marie Le Guay gives recitals at many leading festivals, among them the Festival International de Piano de La Roque d’Anthéron, the MDR Musiksommer and Klavier-Festival Ruhr in Germany and the Lockenhaus Festival in Austria, and regularly performs chamber music, notably with the cellist François Salque, forming an elegiac duo as in their Schubert recording released in 2018 on MIRARE.In the course of a career that began at the age of fifteen, and thanks to her exceptionally open-minded attitude and her inexhaustible musical curiosity, Claire-Marie Le Guay has built up a vast repertoire ranging from Bach to Escaich and is the dedicatee of numerous works by composers of our time."
},
// { id : 26,
//   titleProf: "Céline Moinet",
//   textProf:"Professor at the Hochschule für Musik Carl-Maria von Weber in Dresden.",
//   imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Celine-Moinet-Oboe-Masterclass-1.jpg",
//   instrumentCategory: "Hautbois",
// },
{ id : 27,
  titleProf: "Céline Moinet",
  textProf:"Professor of violin at New England Conservatory in Boston. At the age of 20, she won the Paganini Competition.",
  imageProf : "https://www.salineacademy.com/wp-/uploads/2023/06/Miriam-Fried-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :"Born in Lille in 1984, Céline Moinet studied the oboe and chamber music at the Conservatoire National Supérieur de Musique de Paris in classes led by David Walter and Maurice Bourgue. In 2006, she was awarded a Premier Prix in both disciplines. She also studied the Baroque oboe with Marcel Ponseele and Xenia Löffler. In 2004 and 2005, she completed her orchestral training as a member of the Gustav Mahler Jugendorchester under the direction of Claudio Abbado. After this experience, she was invited to appear as guest principal with leading German orchestras such as the NDR Sinfonieorchester Hamburg, the Deutsches Symphonie-Orchester Berlin, the SWR Radiosinfonieorchester Stuttgart, the Philharmoniker Hamburg, and the orchestra of the Frankfurt Opera. In 2006, she was appointed principal oboe of the Nationaltheater-Orchester Mannheim. Since June 2008, she has occupied the same position with the celebrated Staatskapelle Dresden. In the autumn of 2011, she was invited by the Vienna Philharmonic Orchestra to appear on an extended tour of Asia and Australia.Céline Moinet performs regularly in solo and chamber repertoire. She has performed all the major oboe concertos with the Staatskapelle Dresden, the Prague Philharmonia, the Pacific Music Festival Orchestra, the New Japan Philharmonic, the Kammerorchester Basel, and the Dresdner Kapellsoliste. Via an invitation by Fabio Luisi, she has given recitals and taught masterclasses at the Pacific Music Festival in Sapporo, Japan."
},
{ id : 28,
  titleProf: "Miriam Fried",
  textProf:"Professor of violin at New England Conservatory in Boston. At the age of 20, she won the Paganini Competition.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Miriam-Fried-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :"Miriam Fried has played with virtually every major orchestra in the United States and Europe and has been a frequent guest with the principal orchestras of Boston, Chicago, Cleveland, New York, Philadelphia and Pittsburgh, as well as with the Israel Philharmonic, the London Symphony, the Royal Philharmonic, and the Vienna Symphony.During 2016 she performed all of the sonatas and partitas in several venues including the Ravinia Festival, Belgium, Toronto, Vancouver, Baltimore and in Jerusalem. The Jerusalem concerts were recorded and released in 2017 on the Nimbus label."
},
{ id : 29,
  titleProf: "François Le Roux",
  textProf:"Former professor at the CNSMD of Paris, then at the École Normale de Musique Alfred Cortot of Paris.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Francois-Le-Roux-Voice-Masterclass-1.jpg",
  instrumentCategory: "Voix",
  detailProf :"François Le Roux began studying vocals with François Loup, now a teacher at Peabody-Baltimore, at the age of nineteen. Later, he continued to study under Vera Rosza and Elisabeth Grümmer at the Opéra Studio, Paris."
},
{ id : 30,
  titleProf: "Jens Peter Maintz",
  textProf:"Professor at the Berlin University of the Arts. He formed the cello duo « Cello Duello » with Wolfgang Emanuel Schmidt.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jens-Peter-Maintz-Cello-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle",
  detailProf :" Similarly, Jens Peter Maintz is equally in great demand as a chamber musician. He is a member of the prestigious ‘Spectrum Concerts Berlin’ concert series, and performs with chamber music partners such as Janine Jansen, Boris Brovtsyn, Torleif Thedéen, Hélène Grimaud, Kolja Blacher, Isabelle Faust, Antoine Tamestit, and also the Artemis, Carmina and Auryn Quartets. It is now 25 years since he formed the cello duo ‘Cello Duello’ with Wolfgang Emanuel Schmidt. Together, they perform at the world’s most eminent festivals, such as the Kronberg Festival, the Cello Biennale Amsterdam and the Piatigorsky International Cello Festival."
},
{ id : 31,
  titleProf: "Boris Garlitsky",
  textProf:"Professor at the Berlin University of the Arts. He formed the cello duo « Cello Duello » with Wolfgang Emanuel Schmidt.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Boris-Garlitsky-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :"Born in Russia, Boris Garlitsky received his first music lessons from his father, the author of the standard textbook for young violinists, “Step by Step”. He studied with Professor Yankelevich at the Moscow Conservatory, and many years later, worked as the Concertmaster for the Moscow Virtuosi and the London Symphony Orchestra, the Covent Garden Opera, the Vienna ORF Orchestra, the Hamburg Philharmonic and many more.In 1982, Boris Garlitsky won the Italian Paganini Competition and began his career as a soloist. Since then, he has played, among others, with the London Philharmonic Orchestra, the Vienna Radio Orchestra, the Chamber Orchestra of Philadelphia as well as the Milan based Giuseppe Verdi Orchestra and the British Orchestra of the Age of Enlightenment. His interpretations of Dmitri Shostakovich’s violin concerto with the Orchestra National de Lyon were praised in the press."
},
{ id : 32,
  titleProf: "Tatiana Samouil",
  textProf:"Professor at the Royal Conservatory of Brussels and at the Superior Center of Arts Musikene.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Tatiana-Samouil-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf: "Tatiana Samouil, Belgian by adoption and Russian-Moldovan by origin, has a versatile career: she plays as a soloist with the most prestigious orchestras, participates in festivals as a chamber musician all over the world and is a renowned teacher.Born in St. Petersburg, Tatiana studied in Moldova and then in Moscow. After meeting the legendary Igor Oistrakh, she became his student at the Royal Conservatory of Music in Brussels and moved to Belgium.Winner of the 7 most famous international competitions, (such as the Queen Elisabeth, the Tchaikovsky and the Sibelius…) she is regularly invited as a member of the jury of the Queen Elisabeth Competition, the Ysaye International Violin Competition, the Henri Vieuxtemps Prize and the Solo Violin Competition in Korea. Having recorded 20 CDs, Tatiana has received numerous awards: Diapason d’or, Choc de Classica, Prix Caecilia, Jocker de Crescendo etc.This season, Tatiana plays in Paris, Berlin, Buenos Aires, Bucharest, Madrid, Hong Kong.She is also currently a professor at the Royal Conservatory of Brussels and at the Superior Center of Arts Musikene (San Sebastián)"
},
{ id : 33,
  titleProf: "Till Fellner",
  textProf:"Professor at the Zurich Hochschule der Künste. Jury president at the Ferruccio Busoni International Piano Competition in 2019.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Till-Fellner-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :"Originally from Vienna, Austria, Till Fellner studied with Helene Sedo-Stadler before going on to study privately with Alfred Brendel, Meira Farkas, Oleg Maisenberg, and Claus-Christian Schuster.The ECM label, for whom Till Fellner is an exclusive recording artist, has released the first book of The Well-Tempered Clavier and the Two & Three-Part Inventions of J. S. Bach, Beethoven’s Piano Concertos Nos. 4 & 5 with the Montreal Symphony Orchestra and Kent Nagano, chamber music by Harrison Birtwistle. In 2016, Alpha Classics released the recording of the piano quintet by Johann Brahms with the Belcea Quartet. This recording received the “Diapason d’Or de l’Année”. Two years later, a CD entitled Till Fellner in Concert, a live recording featuring the works of Franz Liszt and Beethoven was publicly released.Since 2013, Till Fellner has taught at the Zurich Hochschule der Künste. In 2019, he was jury president at the 62nd Ferruccio Busoni International Piano Competition in Bolzano."
},
{ id : 34,
  titleProf: "Michel Dalberto",
  textProf:"Professor at the CNSMD of Paris. From 1991 to 2009, he chaired the jury of the Clara Haskil Competition.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Michel-Dalberto-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :"Born in Paris in 1955 into a family with origins in the Dauphiné and the Italian Piedmont, Michel Dalberto began playing the piano at the age of three. He played in public for the first time at the age of five and a half, and at the early age of thirteen joined Vlado Perlemuter’s class at the Paris Conservatoire.He was appointed Professor at the Paris Conservatoire in September 2011 and has a regular relationship with the Tianjin Conservatory. He has previously been invited to give masterclasses at the Accademia Pianistica in Imola, the Hochschule in Hanover, the Royal College in Manchester, Seoul University, the Tel Hai International Piano Academy, the Hong Kong Academy for Performing Art, Toho University in Tokyo, and the Lang Lang Piano School in Shenzhen. In 1996, the Minister of Culture made him a Chevalier in the National Order of Merit in recognition of his artistic activity."
},
{ id : 35,
  titleProf: "Anne Gastinel",
  textProf:"Professor at the CNSMD of Lyon. Anne Gastinel won numerous prizes in major international competitions (Scheveningen, Prague, Rostropovitch).",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Anne-Gastinel-Cello-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle",
  detailProf :"Anne Gastinel won numerous prizes in major international competitions (Scheveningen, Prague, Rostropovitch) and began to appear all over Europe, making a lasting impact on the general public in the 1990 Eurovision Competition.Unanimously recognized as an ambassador of the French cello school, she was selected to play for the term of one year: the legendary Matteo Gofriller cello that once belonged to Pablo Casals. In 2006, Anne Gastinel was awarded the Victoire de la Musique in the category of ‘Soloist of the Year’ and ‘Best Recording’."
},
{ id : 36,
  titleProf: "Svetlana Makarova",
  textProf:"Professor at the Haute Ecole de Musique in Lausanne in Switzerland.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Svetlana-Makarova-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :"Svetlana Makarova was born in Moscow in 1981. She started playing the violin at the age of five in a class led by celebrated Russian artist, Ludmila Egorova. At the early age of ten, she won First Prize at the Moscow International Youth Tchaikovsky Competition. Hereafter, she won many more esteemed prizes at numerous state and international competitions. In 2005, Makarova graduated the Moscow State Tchaikovsky Conservatory, and in 2008 finished her postgraduate studies with Professor M. Glezarova. rom 2005-2008, Makarova taught at the famous Gnessin’s Music College in Moscow. Subsequently, she was invited by Pavel Vernikov to collaborate with him in numerous masterclasses in Italy, Israel, and Austria. Since 2010, she has been teaching at the Scuola di Musica di Fiesole in Italy. Until 2013, she worked as Pavel Vernikov’s assistant at the Haut Ecole de Musique de Lausanne (site de Sion) in Switzerland, and with many masterclasses in Europe and Asia.Since 2014, she has been a violin professor at the Haut Ecole de Musique de Lausanne in Switzerland. She plays a violin by Nicola Gagliano, made in 1738"
},
{ id : 37,
  titleProf: "Pavel Vernikov",
  textProf:"Professor of the highly esteemed Konservatorium Wien University. Professor at the Haute Ecole de Musique in Lausanne.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Pavel-Vernikov-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :"Pavel Vernikov, a student of David Oistrach and S. Snitkowsky, gained his reputation as a virtuoso violinist over twenty years ago. Some prominent prizes he has won include, but are not limited to: the International ARD Violin Competition in Munich and the Grand Prix at the International Violin Competition “Vittorio Gui” in Florence. As an educator, Vernikov was the professor at the Conservatoire National Supérieur de Musique de Lyon. Currently, he is a professor of the highly esteemed Konservatorium Wien University,  and at the Haute Ecole de Musique de Lausanne, site de Sion. His alumni consist of acclaimed musicians. Among them are: Massimo Quarta (1. Prize Paganini International Violin Competition, Genua), Fumiaki Miura (1. Prize Hannover International Violin Competition), Lorenza Borrani (Leader of the Chamber Orchestra of Europe), Fanny Clamagirand (1. Prize Fritz Kreisler International Violin Competition, Vienna and 1. Prize International Monte Carlo Violin Competition), and Miki Kobayashi (2. Prize Wieniawski Competition). In 2013, he was appointed Artistic Director of the Sion Festival in Switzerland. Pavel Vernikov plays the beautiful Giovanni Battista Guadagnini violin, Milano 1751, owned by the family of Tibor Varga."
},
{ id : 38,
  titleProf: "Mihaela Martin",
  textProf:"Professor at the University of Music in Cologne. Professor at the Haute Ecole de Musique in Geneva.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Mihaela-Martin-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :"Romanian-born artist Mihaela Martin is known as one of the most outstanding violin virtuosos of her generation. She began taking lessons with her father when she was five years old. Later, she studied with Stefan Gheorghiu, a pupil of George Enescu and David Oistrakh. At nineteen, Mihaela Martin won the Second Prize in the International Tchaikovsky Competition in Moscow, followed by other prominent prizes in Montreal, Sion, and Brussels. Subsequently, her international career was launched after receiving First Prize at the International Violin Competition of Indianapolis.She has performed with leading orchestras such as the BBC Symphony, the Royal Philharmonic, the Montreal Symphony Orchestra, the Mozarteum Orchestra of Salzburg, and the Leipzig Gewandhaus Orchestra. Furtermore, she has worked with conductors such as Kurt Masur, Nikolaus Harnoncourt, Charles Dutoit, and Neeme Järvi. In the past season, Mihaela Martin not only performed as a soloist, but also appeared at chamber music festivals in Italy, Norway, the United Kingdom, France, Israel, Germany, Greece, Romania, and Switzerland. Together with Daniel Austrich, Nobuko Imai, and Frans Helmserson, she is a permanent member of the Michelangelo String Quartet, which she cofounded in 2003.Mihaela Martin is a professor at the University of Music in Cologne and at the Haute Ecole de Musique in Geneva, and has taught at the Académie musicale de Villecroze. In addition, she teaches masterclasses all over the globe. She is a regular jury member at important international competitions, such as the Queen Elisabeth (Belgium), Indianapolis (USA), Enescu (Romania), and Tchaikovsky (Russia)."
},
{ id : 39,
  titleProf: "Jacques Rouvier",
  textProf:"Professor at the CNSMD in Paris and at the Berlin University of the Arts.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jacques-Rouvier-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :"Jacques Rouvier was born in Marseilles into a family of musicians. He attended the CNSMD in Paris (Conservatoire National Supérieur de Musique et de Danse), where he was taught by Vlado Perlemuter, Pierre Sancan, and Jean Hubeau. He won first prizes in both piano and chamber music. Rouvier then decided to broaden his knowledge about wind section and leading orchestra at the CNSMD too. He owes much to Pierre Barbizet and Jean Fassina. Rouvier won several competitions such as the “Giovan Battista Viotti” International Music Competition, Maria Canal International Music Competition, the European Broadcasting Union Competition, the Long-Thibaud Competition, and the Competition of the Fondation de la Vocation. In 1970, he founded the Rouvier-Kantorow-Muller trio, with whom he still performs regularly. He took part in many festivals and academies (Prades, Spoleto, Kuhmo, Aix-en-Provence, Hamamatsu) and gave masterclasses all over the world. He was awarded Grand Prix du Disque for his recording of the complete piano works of Maurice Ravel, as well as the sonatas of Ravel and Debussy with J.J. Kantorow. Rouvier also recorded the whole work of Debussy and some thirty other CDs. He was invited to be a jury member for international and prestigious competitions, like the Tchaïkovsky, Leeds, Santander, Rubinstein, and Marguerite Long Competition. Since 1979, he has taught at the CNSMD in Paris and at the Berlin University of the Arts."
},
{ id : 40,
  titleProf: "Thérèse Fahy",
  textProf:"Professor at the Royal Irish Academy of Music.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Therese-Fahy-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :" Dublin-born Thérèse Fahy, one of Ireland’s foremost pianists, enjoys an active performing and teaching career at home and abroad. Her regular recital and concerto appearances throughout Europe and the United States have met with critical acclaim, as have her numerous broadcasts for both RTÉ and BBC.In recent seasons, Thérèse has toured the east coast of the United States, with a recital- program of solo Irish contemporary piano music supported by Culture Ireland and the Fulbright Commission, and in 2012 with performances of the 24 Debussy Préludes, to celebrate the 150th anniversary of the composer’s birth. This program was toured extensively through Europe and Ireland. Other engagements over the last six years have included solo recitals, lecture-recitals and masterclasses in France, UK, Italy, Poland, Spain, USA, the Czech Republic, Holland, Israel, Ethiopia and Ireland. Thérèse has also served on the international juries of the Dublin International Piano Competition, the Manchester International Concerto Competition in Great Britain, the Baltic International Piano Competition and the Scriabin International Piano Competition, Italy."
},
{ id : 41,
  titleProf: "Frans Helmerson",
  textProf:"Professor at the Musikhochschule in Cologne and at the Escuela Superior de Musica Reina Sofia in Madrid.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Franz-Helmerson-Cello-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle",
  detailProf :" Born in 1945 in Sweden, Frans Helmerson began playing the cello at the age of eight. After studying in Sweden, Rome, and London under the tutelage of Guido Vecchi, Giuseppe Selmi, William Pleeth, and later from Mstislav Rostropovich. His solo career began in Stockholm, Sweden. Since the early days of his career, he has performed with some of the most esteemed orchestras across the five continents, performing with leading conductors of our time – Seiji Ozawa, Colin Davies, Neeme Järvi, Evgeni Svetlanov, Esa-Pekka Salonen, Herbert Blomstedt, Sergiu Comissiona, Rafal Frübeck de Burgos, and Kurt Sanderling. His passion for chamber music has led him to numerous festivals, including the International Umeea-Korsholrn Festival in northern Sweden and Finland. He has performed in Verbier, Prades, Naantali, Kuhmo, and Ravinia. Presently, Helmerson works regularly as a conductor with Scandinavian orchestras. As an educator, he teaches at the Musikhochschule in Cologne, where he is based, and at the Escuela Superior de Musica Reina Sofia in Madrid. He taught at the Villecroze Music Academy in 2012, 2014, and 2020."
},
{ id : 42,
  titleProf: "Stephen Kovacevich",
  textProf:"He has conducted the Chamber Orchestra of Europe.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Stephen-Kovacevich-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :"Stephen Kovacevich is widely recognised as one of the most revered artists of his generation.  With an international career spanning more than six decades, he has long been recognised as one of the most searching interpretors, “A musician completely absorbed in his craft, his interpretations are like no one else’s and always eminate directly from the heart: musical messages of wisdom, peace, resignation, and hope” (The Washington Post.Kovacevich is known for never being afraid to take both technical and musical risks in order to achieve maximum expressive impact."
},
{ id : 43,
  titleProf: "Sung-Won Yang",
  textProf:"Professor at the School of Music Yonsei University in Seoul and visiting professor at the Royal Academy London.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Sung-won-Yang-Cello-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :" Cellist Sung-Won Yang has performed throughout the world as a soloist and chamber musician. He has given solo and chamber music concerts in prestigious venues, such as Alice Tully Hall at Lincoln Center in New York, the Salle Pleyel and Théâtre des Champs Elysées in Paris, the Concertgebouw in Amsterdam, the Terrace Theater at the Kennedy Center in Washington DC, the Musikverein in Vienna, the Opera City Hall in Tokyo, Symphony Hall in Osaka, and the National Center for the Performing Arts in Beijing. His recitals have also led to other leading cities, such as London, Rome, Frankfurt, Madrid, Prague, Helsinki, Boston, Seattle, Tel Aviv, Shanghai, Sydney, and many others. Published via EMI-Korea, his album entirely devoted to Kodály, was “the editor’s choice of the month” by Gramophone Magazine, and “critic’s choice of the year” by Gramophone Magazine in the UK (December 2003), nominated for best solo album in the Edison Awards in the Netherlands. His other recordings for EMI, are works by Rachmaninoff and Chopin, the complete J.S. Bach’s suites for cello solo, and the complete Beethoven sonatas and variations for cello and piano."
},
{ id : 44,
  titleProf: "Philippe Bernold",
  textProf:"Professor of flute and chamber music at the CNSMD of Paris.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Philippe-Bernold-Flute-Masterclass-1.jpg",
  instrumentCategory: "Flute",
  detailProf :"Philippe Bernold began his musical studies in Colmar, France, studying the flute and later composition and conductingunder René Matter, himself a student of Charles and Fritz Münch.He then attended the Paris Conservatory, where he earned the First prize in flute and the next year, at the age of 23, was appointed first flute of the National Opera Orchestra of Lyon.  In 1987 he won First Prize in the Jean-Pierre Rampal International Competition in Paris.This award allowed him to start a career as a soloist, performing with world famous artists and orchestras such as: M. Rostropovitch, R. Capuçon, G. Opitz, A. Tharaudwith Paris Orchestra, Manchester Hallé Orchestra, Tapiola Sinfonietta, National Orchestra of Lyon, Tokyo and Kyoto Symphony Orchestra…,  he has been directed by S. Bychkov, J. E. Gardiner, L. Maazel, K. Nagano, Sir Y. Menuhin, M. Inoué, T. Koopman, in concert halls such as the Royal Festival Hall in London, Pleyel Hall and Chatelet Theater in Paris, Cologne Philharmonie, Warsaw Philharmonic, BunkaKaikan in Tokyo, Seoul Art Center, Tchaïkovsky Conservatory in Moscow, as well as at the Festivals of Aix-en-Provence, Cannes, Evian, Strasbourg, Radio France, Varna…"
},
{ id : 45,
  titleProf: "Peter Bruns",
  textProf:"Professor at the Mendelssohn Hochschule Leipzig.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Peter-Bruns-Cello-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle ",
  detailProf :"."
},
{ id : 46,
  titleProf: "Olivier Charlier",
  textProf:"Revealed by the Long-Thibaud Foundation competition. Winner of the Young Concert Artists International Audition in 1989.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Olivier-Charlier-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon ",
  detailProf :"A rare conviction that only can confer a sovereign control, a singular presence made by powerful inner light and mystery: Olivier Charlier counts undoubtedly among the great violinists. He conquers the public with the natural grace of pure playing, as an exceptionally dedicated and gifted performer whose virtuosity supremely serves the music.Of a remarkable precocity, he enters the Paris Conservatoire at the age of 10, and received illustrious support, as Nadia Boulanger, Yehudi Menuhin and Henryk Szeryng. Follows an impressive series of international rewards: Competition of Munich, Montreal, Sibelius, Jacques Thibaud, Indianapolis, Young Concert Artists (New york)."
},
{ id : 47,
  titleProf: "Michel Béroff",
  textProf:"Professor at the CNSM of Paris. From 1991 to 2009, he chaired the jury of the Clara Haskil Competition.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Michel-Beroff-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano ",
  detailProf :"Michel Beroff was born in France in 1950. After graduating from the Paris conservatoire in 1966, he won the following year the first prize at the first international Olivier Messiaen piano competition. He has been since considered one of the most outstanding interpreter of Messiaen’s music. He then went on to play with the most prestigious orchestras around the world under the direction of such conductors as Abbado, Barenboim, Bernstein, Boulez, Dohnanyi, Dorati, Dutoit, Eschenbach, Gielen, Inbal, Jochum, Leinsdorf, Masur, Ozawa, Previn, Rostropovitch, Sinopoli, Solti, Tennsted, Tilson-Thomas, Zinman. As a chamber music partner , he has been very active playing with Martha Argerich , Barbara Hendricks Jean- Philippe Collard, Augustin Dumay, Pierre Amoyal, Lynn Harrell."
},
{ id : 48,
  titleProf: "Nathan Braude",
  textProf:"Professor at the Royal College of Music of London. 1st viola of the Gurzenich Orchester Cologne since 2016.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Nathan-Braude-Viola-Masterclass-1.jpg",
  instrumentCategory: "Violon ",
  detailProf :"The Belgian-Israeli violist Nathan Braude has performed in many of the world’s most prestigious concert venues including the Wigmore Hall in London, Théâtre de la Ville in Paris, Amsterdam Concertgebouw and the Palais des Beaux-Arts in Brussels.Nathan Braude has also appeared as a soloist with numerous orchestras including the Brussels Philharmonic, Orchestre National de Lille, Orchestra della Svizzera italiana, Australian Chamber Orchestra, Orchestre Philharmonique Royal de Liège, Symfonieorkest Vlaanderen, Limburgs Symfonie Orkest and Solistes Européens Luxembourg. In September 2016 Nathan became the new principal violist at the Gurzenich Orchester, Koln.Festival appearances include Progretto Martha Argerich in Lugano, Ravinia Festival in Chicago and  Festival de Radio France in Montpellier. Since 2010 Nathan regularly performs in duo recitals together with his wife Polina Leschenko.His début recording for the Fuga Libera label with the complete works for viola, by the Belgian composer Joseph Jongen, has been released to great critical acclaim. Other recordings include the Dvorak piano quartet op.87 released on EMI Classics as part of the Martha Argerich and Friends: Live from the Lugano Festival 2012” series and Brahms horn trio (viola version) for the Warner Classic label. Nathan Braude plays a viola by Pietro Giovanni Mantegazza (Milano, 1772)."
},
{ id : 49,
  titleProf: "Margreet Honig",
  textProf:"She has gained international recognition for being a vocal coach to many singers who have developed advanced careers in professional singing.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Margreet-Honig-Voice-Masterclass-1.jpg",
  instrumentCategory: "Voix ",
  detailProf :"The Dutch soprano Margreet Honig first studied at the Amsterdam Conservatory with Annie Hermes and Corrie Bijster. She then went to the United States to study with Evelyne Fear and then to Paris, under the direction of Pierre Bernac, where she decided to devote herself to the French musical repertoire. She gave several recitals with the pianist Rudolf Jansen, and recorded with the Radio Chamber Orchestra, conducted by Kenneth Montgomery.Margreet Honig has been teaching voice for the past thirty years. She worked for many years at the Rotterdam Conservatory and the Amsterdam Conservatory (formerly the Sweelink Conservatory). Margreet is regularly invited to give masterclasses and performance courses in Europe and the United States. She teaches at the conservatories of Zurich, Basel, Stuttgart, Hamburg and Versailles, at the CNSM in Paris, at the Aix en Provence Festival Academy, at the Curtis Institute of Music in Philadelphia and at the Royal Academy in London. She also works regularly at the Bavarian State Opera in Munich, the Basel Opera and the Latvian National Opera."
},
{ id : 50,
  titleProf: "Marie-Josèphe Jude",
  textProf:"Professor at the CNSMD of Paris. In October 2017, she was appointed President of the Nice International Summer Academy.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Marie-Josephe-Jude-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano ",
  detailProf :"Marie-Josèphe Jude was born in Nice in 1968 from a French father and a sino-Vietnamese mother.  She started to learn piano and harp in her home city before joining the Conservatoire de Paris encouraged by G. Cziffra. She worked with Aldo Ciccolini (piano) and Jean Hubeau (chamber music) and was awarded a first prize in Piano and a concert licence in harp at the Ecole Normale in Paris. She then entered the third cycle in Jean-Claude Pennetier’s class.At that time, she regularly attended Maria Curcio-Diamand’s lessons in London.  In 1986, she met the composer Maurice Ohana and became one of her favourite performers.  She was a finalist at the Clara Haskil Competition in 1989 and won the Victoire de la Musique  in the category “New Talent” in 1995.This is when her carreer developped internationally, she has appeared in halls and festivals all over the world : from Montpellier to bath, from the Roque d’Anthéron to Kuhmo, from Bagatelle to Locarno, from Colmar to Québec, from Nantes to Tokyo (Folle Journée)…."
},
{ id : 51,
  titleProf: "Maarten Koningsbergerr",
  textProf:"He has taught singing at the Amsterdam Conservatory of Music, the CNSMD of Paris and the Centre de Musique Baroque de Versailles.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Marteen-Koningsberger-Voice-Masterclass-1.jpg",
  instrumentCategory: "Voix ",
  detailProf :" The musical interests of Dutch baritone Maarten Koningsberger encompass early music, opera, oratorio, romantic song and contemporary repertoire. This diversity of styles is reflected in his concert- and recital programs which bring him to concerthalls and festivals all over the world (Wigmore Hall London, Concertgebouw Amsterdam, Carnegie Hall New York, Staatsoper Berlin, Theater an der Wien, Philharmonie München, Cité de la Musique Paris, Beijing Concert Hall, Baxter Hall Cape Town and more).He sings with orchestra’s such as Les Arts Florissants, the Concertgebouw Orchestra, the Orchestra of the Age of Enlightenment, the Academy of Ancient Music, der Akademie Alte Music Berlin, Tafelmusic Toronto, the Hong Kong Philharmonic and Singapore Philharmonic under the baton of William Christie, Jeffrey Tate, Gustav Leonhardt, Mark Minkowski, Ton Koopman, Richard Egarr Gennady Roshdenstvenski, René Jacobs, Jan Willem de Vriend, Marin Alsop, Jaap van Zweden and Christophe Rousset."
},
{ id : 52,
  titleProf: "Kim Kashkashian",
  textProf:"She coaches chamber music and viola at New England Conservatory of Music. She won a Grammy Award for her recording of Ligeti and Kurtag solo viola works in 2013.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Kim-Kashkashian-Viola-Masterclass-1.jpg",
  instrumentCategory: "Violon ",
  detailProf :" Hailed as “an artist who combines a probing, restless intellect with enormous beauty of tone,” Ms. Kashkashians’ work as performing and recording artist and pedagogue has been recognized worldwide.She won the coveted Grammy Award for her recording of Ligeti and Kurtag solo viola works in 2013, and received the George Peabody Medal and Switzerland’s Golden Bow Award for her contributions to music. In 2016, she was elected a Fellow of the American Academy of Arts and Sciences, and in 2020, was named an Honorary member of the Royal Academy of Music.As soloist Kashkashian has appeared with the orchestras of Berlin, London, Vienna, Milan, New York and Cleveland in collaboration with Eschenbach, Mehta, Welser-Moest, Kocsis, Dennis Russel Davies, Blomstedt, and Holliger.Recital appearances include the great halls of Vienna, Rome, Paris, Berlin, Munich, Tokyo, Athens, London, New York, Boston, Chicago, San Francisco and Philadelphia where Ms. Kashkashian appears with the Trio Tre Voce, and in duo partnerships with pianist Robert Levin and percussionist Robyn Schulkowsky.She is also a regular participant at the Verbier, Salzburg, Lockenhaus, Marlboro, and Ravinia festivals."
},
{ id : 53,
  titleProf: "Kristof Barati",
  textProf:"He is Artistic Director of the Kaposvár International Chamber Music Festival.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Kristof-Barati-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon ",
  detailProf :"Hungarian violinist Kristóf Baráti is recognised increasingly across the globe as a musician of extraordinary quality with a vast expressive range and impeccable technique. Applauded repeatedly for the poetry and eloquence that he brings to his playing, he has been described as “a true tonal aesthete of the highest order”.n recent seasons, Baráti has performed at the Hollywood Bowl with the Los Angeles Philharmonic, at London’s Royal Festival Hall with the London Philharmonic Orchestra and in 2019 he was the featured soloist in the opening concert of the the Verbier Festival. Baráti has played with orchestras such as Zurich Tonhalle, Oslo Philharmonic, Orchestre National de France, ORF Vienna Radio Symphony, Orchestre Symphonique de Montreal, BBC Scottish Symphony, BBC Philharmonic and Hague Philharmonic orchestras. He performs regularly with Gergiev and the Mariinsky Orchestra both in Russia and on tour around the world including in the US and China. Highlights of his 2020/21 season include performances with the Budapest Festival and Bern Symphony orchestras, and debuts with the Bavarian Radio Symphony and Israel Philharmonic orchestras amongst others."
},
{ id : 55,
  titleProf: "Lars Anders Tomter",
  textProf:"Professor at the State Academy in Oslo. Professor at the Royal Danish Music Academy in Copenhagen.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Lars-Anders-Tomter-Viola-Masterclass-1.jpg",
  instrumentCategory: "Violon ",
  detailProf :"Lars Anders Tomter, born in Hamar, Norway, is one of the most outstanding violists of our time. He studied violin and viola from the age of eight with Leif Jørgensen, a teacher at the Oslo Conservatory of Music and the Norwegian State Academy. He continued his studies with Max Rostal and Sándor Vegh. He won a special prize for his performance of Bartók’s Viola Concerto at the International Viola Competition in Budapest in 1984 and the Maurice Vieux International Competition in Lille in 1986.Lars Anders Tomter is the dedicatee of the concertos of composers Ragnar Söderlind, Erkki-Sven Tüür, Rolf Wallin and Anders Eliasson, for which he has given the world premieres. In 2011 he recorded Vagn Holmboe’s Viola Concerto with the Norrkoping Symphony Orchestra, published on the dacapo label. In 2015 he recorded Poul Ruders Viola Concerto with the Aarhus Symphony Orchestra and in 2017 he performed Egil Hovland’s Viola Concerto with the Oslo Philharmonic Orchestra."
},
{ id : 56,
  titleProf: "Jean-Paul Fouchécourt",
  textProf:"He has been directing the destiny of the Studio de l'Opéra de Lyon (SOL).",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jean-Paul-Fouchecourt-Voice-Masterclass-1.jpg",
  instrumentCategory: "Voix",
  detailProf :" Combining sensibility, elegance of singing, diction and malice mixed with a strong stage presence, Jean-Paul Fouchécourt has gained an international reputation by his portraits of Platté de Rameau and Arnalta (l’Incoronazione di Poppea) of Monteverdi, then those of these so-called “character” roles such as Offenbach’s Four Valets (Offenbach’s Tales), Chabrier’s Phew (The Star), Ravel’s Child and Spells and Torquemada (The Spanish Hour).material-symbols-outlined it is with the classical saxophone and conducting that his music life begins before the singer Cathy Berberian encourages him to work on his voice. In 1986, he discovered the world of early music with William Christie in the ensemble Les Arts Florissants and participated in the now historic recreation of the Opera Atys de Lully at the Opéra-Comique in Paris and at the craze for French Baroque music. With Marc Minkowski, he recorded the title roles of Hippolyte et Aricie by Rameau, Titon and Aurore by Mondonville and Acis and Galatée by Lully and Hervé Niquet with numerous religious plays. He made his debut in 1993 at the Amsterdam Opera in L’Incoronazione di Poppea with Christophe Rousset."
},
{ id : 57,
  titleProf: "Jean-François Heisser",
  textProf:"From 1991 to 2016, he was a professor at the CNSMD of Paris. He is the President of the Maurice Ravel International Academy.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jean-Francois-Heisser-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :" Jean-François Heisser is a well-rounded artist, leading a versatile career as a pianist, conductor and teacher, fueled by a vast cultural knowledge and tireless intellectual curiosity.Born in Saint-Etienne, he is the disciple and heir of Vlado Perlemuter, Henriette Puig-Roget and Maria Curcio.He was profesor at the Paris Conservatoire National Supérieur de Musique from 1991 till 2016. Among his talented students are Bertrand Chamayou and Jean-Frédéric Neuburger, with whom he has developed a relationship of close musical complicity. He now balances his career as a soloist with his activities as the musical director of the Nouvelle- Aquitaine Chamber Orchestra (since 2001), and as guest conductor and also artistic director of various institutions and major musical productions."
},
{ id : 58,
  titleProf: "Günter Pichler",
  textProf:"Founder of the Alban Berg Quartett. Teacher at the European Centre for Chamber Music - ProQuartet.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Gunter-Pichler-Chamber-music-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :"Günter Pichler was born and raised in Kufstein, Tyrol, Austria. He was accepted at the University of Music and Performing Arts, Viennain 1955. He joined the Vienna Symphony as concert master under Wolfgang Sawallisch at the age of 18. At 21, he was made concert master by the Vienna Philharmonic thanks to a tie-breaking vote on hisappointment by conductor Herbert von Karajan.In 1970 Günter Pichler founded the Alban Berg Quartett and was the first violin of this world famous string quartet until it disbanded in 2008.From 1963 to 2009 he taught at the University of Music and Performing Arts, Vienna as a professor, from 1993 to 2012 he was a professor at Cologne University of Music. In 2007 he was appointed head of the International Institute for Chamber Music at the Escuela Superior de Musica Reina Sofia in Madrid. In addition he teaches at several summer academies, including Pro Quartet Paris, Accademia Chighiana Siena and the Misqua Montreal. Many of his students received international prizes, have become concert masters in important orchestras, or made a name for them selves with solo careers. Also among his students are String Quartets such as the Artemis, Aron, Aris, Belcea,  Acies, Amaryllis, Casals, Cavaleri, Eliot, Fauré, Finzi, Notos, Minetti, Piatti, Simply, Schumann, van Kuijk, Vision, Voce and  the Trio con brio, Atos-, Eggner-, Morgenstern-,  Zadig Trios."
},
{ id : 59,
  titleProf: "Goyrgy Pauk",
  textProf:"Professor at the Royal Academy of Music in London. He offers masterclasses at Curtis, Peabody, Yale, Cleveland, Oberlin, Manhattan School, San Francisco, and Juilliard School and other.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Gyorgy-Pauk-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :"Recognised as one of the leading violinist of his generation, Gyorgy Paukwas born in Budapest, Hungary and received his musical education at the renown Franz Liszt Music Academy . Before settling in London in 1961, he already won First Prize of the PAGANINI Competition in Genova , The Premier Grand Prix of the JACQUES THIBAUD Competition in Paris, First Prize  of the MUNICH Sonata Competition and gave numerous concerts all over Eastern Europe.He made his London debut in the Wigmore Hall in 1962 receiving outstanding reviews in the press, followed by his orchestral debut in the Royal Festival Hall, with the London Symphony Orchestra under Lorin Maazel. He made his U.S. Debut with the Chicago Symphony at the invitation of Sir George Solti."
},
{ id : 60,
  titleProf: "Hugh Tinney",
  textProf:"Professor at the Royal Irish Academy of Music in Dublin.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Hugh-Tinney-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :"Born in Dublin in 1958, Hugh Tinney first came to international recognition by winning the First Prize in two international competitions, the 1983 Pozzoli in Italy and the 1984 Paloma O’Shea in Spain. Since then, he has performed in more than 35 countries throughout Europe, the United States, Latin America and the Far East. Festival engagements have taken him to Belgium, the Czech Republic, Spain, Finland, France, Japan, and the USA. Likewise, he has been broadcast on radio or TV in more than 15 countries.In 1987, he was a prize-winner in the Leeds Piano Competition.  Two years later he made his debut at the BBC ‘Proms’ playing Beethoven’s Emperor Concerto with the BBC Welsh Symphony Orchestra, and there followed a busy career in the U.K., performing with major orchestras such as the London Philharmonic, the Philharmonia, the Royal Philharmonic, the City of Birmingham Symphony, the Royal Liverpool, the Royal Scottish and the BBC National of Wales."
},
{ id : 61,
  titleProf: "Finghin Collins",
  textProf:"He will chair the jury of the Clara Haskil Competition in 2023 and 2025. He was a member of the jury of the Clara Haskil Competition in 2021 and the Dublin International Piano Competition in 2022.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Finghin-Collins-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :"One of Ireland’s most successful musicians, Finghin Collins wasborn in Dublin in 1977 and, following initial lessons with his sister Mary, studied piano at the Royal Irish Academy of Music with John O’Conor and at the Geneva Conservatoire with Dominique Merlet. Winner of the RTÉ Musician of the Future Competition in 1994 and the Classical Category at the National Entertainment Awards in Ireland in 1998, he went on to take first prize at the Clara Haskil International Piano Competition in Switzerland in 1999. Since then he has continued to enjoy a flourishing international career that takes him all over Europe and the United States, as well to the Far East and Australia.Collins has performed with such orchestras as the Chicago Symphony Orchestra, Houston Symphony Orchestra, London Philharmonic Orchestra, Royal Philharmonic Orchestra, Rotterdam Philharmonic Orchestra, Budapest Festival Orchestra, Orchestra of the Eighteenth Century, Orchestre de la Suisse Romande, Gulbenkian Orchestra, Seoul Philharmonic Orchestra, BBC Symphony Orchestra, BBC Philharmonic Orchestra, Royal Liverpool Philharmonic Orchestra, Bournemouth Symphony Orchestra and the City of Birmingham Symphony Orchestra, garnering consistent praise from critics and public alike. Conductors with whom he has collaborated include Frans Brüggen, Myung-Whun Chung, Christoph Eschenbach, Hans Graf, Emmanuel Krivine, Nicholas McGegan, GianandreaNoseda, SakariOramo, TadaakiOtaka, Heinrich Schiff, Vassily Sinaisky, Leonard Slatkin and GáborTákacs-Nagyy."
},
{ id : 62,
  titleProf: "Gerard Poulet",
  textProf:"Former professor at the CNSMD of Paris, the CNR of Paris, and the Ecole Normale de Musique of Paris. Professor at the Showa University of Music in Japan since 2010.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Gerard-Poulet-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :"Gérard Poulet started as a child prodigy. His father, the violinist and conductor Gaston Poulet had the privilege of giving the first performance of Debussy’s Sonata in 1917, with the author at the piano. Gérard entered the Conservatoire National Supérieur in Paris at the age of eleven, and graduated two years after with a unanimously awarded first prize. Aged eighteen, he won the first prize at the Paganini Competition in Genoa.As he continued to benefit from the teaching of such masters as Zino Francescatti, Yehudi Menuhin, Nathan Milstein and especially Henryk Szeryng, who considered him his “spiritual heir”, numerous concerts were to follow, and his career developed rapidly worldwide: from Europe to Asia, form America to Africa, where he plays today regularly with the finest orchestras, while he takes part in the most prestigious musical seasons, including those of Radio France, the Musée d’Orsay."
},
{ id : 63,
  titleProf: "Dmitry Sitkovetsky",
  textProf:"International soloist and conductor.",
  imageProf : "https://www.gsoguild.org/wp-content/uploads/2019/04/dima-2015.jpg",
  instrumentCategory: "Violon",
  detailProf :"A Renaissance man and a creative force, Dmitry Sitkovetsky is recognized world-wide for his versatility, being a violinist, conductor, creator, recording artist, transcriber, facilitator, and educator. He has made a considerable impact on musical society, and his interests cover every aspect of musical life.  Over the four decades since the launch of his career in Vienna’s Musikverein in 1979, Dmitri Sitkovetsky has worked closely with many of the world’s great conductors and orchestras.They include: Sir Neville Marriner, Mariss Jansons, Sir Colin Davis, Yuri Temirkanov; Berlin PO, Royal Concertgebouw Orchestra, London Symphony, Philharmonia, Chicago Symphony, Cleveland Orchestra, New York Philharmonic, LA Philharmonic, Philadelphia, Leipzig Gewandhaus, Bayerischer RF, Munich PO, and the NHK Symphony. His celebrated career as a violinist is documented in an extensive discography of more than forty recordings, reflecting the impressive breadth of his repertoire from J.S. Bach to Rodion Shchedrin."
},
{ id : 64,
  titleProf: "Clive Greensmith",
  textProf:"Professor at Colburn School. Member of the world-renowned Tokyo String Quartet and Montrose Trio.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Clive-Greensmith-Cello-Masterclass-1.jpg",
  instrumentCategory: "Musique de chambre",
  detailProf :"From 1999 until its final season in 2013, Clive Greensmith was a member of the world-renowned Tokyo String Quartet, giving over one hundred performances each year in the most prestigious international venues, including New York’s Carnegie Hall, Sydney Opera House, London’s South Bank, Paris Chatelet, Berlin Philharmonie, Vienna Musikverein, and Suntory Hall in Tokyo. He has collaborated with international artists such as Andras Schiff, Pinchas Zukerman, Leon Fleisher, Lynn Harrell, Dmitry Sitkovetsky, Alicia de Larrocha, and Emanuel Ax. Mr. Greensmith has given guest performances at prominent festivals worldwide. In North America he has performed at the Aspen Music Festival, Marlboro Music Festival, Music@Menlo, La Jolla SummerFest, Santa Fe Chamber Music Festival, Cleveland Chamber Fest, and the Ravinia Festival."
},
{ id : 65,
  titleProf: "Davide Formisano",
  textProf:"Professor at Musikhochschule in Stuttgart, principal flutist at the Scala.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Davide-Formisano-Flute-Masterclass-1.jpg",
  instrumentCategory: "Flute",
  detailProf :"“Davide is the most brilliant and talented flutist I ever listened to. I believe sooner or later he will become an absolute international superstar. Davide Formisano was born in Milan in 1974. He graduated with the highest marks plus distinction under the guide of M° C. Tabarelli, Jean-Claude Gérard at Stuttgart Musikhochschule and Aurele Nicolet in Basel.At just seventeen, he took part in the “Jean Pierre Rampal Concourse” in Paris, gaining the “Prix Special du Jury”. During the next few years he won a prize at Kobe International Flute Competition, 1st prize at the Budapest Flute Competition and 2nd prize (1st not assigned) at the outstanding ARD Concourse in Munich.As the first italian flutist to receive such honours in 1995 he obtained the solo flute role at the Hamburg Philharmonisches Staatsorchester, getting the same position in the Netherlands Radio Philharmonic Orchestra one year later. Since 1997 he is principal flute in the “Orchestra del Teatro alla Scala” and in the same Philharmonic Orchestra. His position there allowed him to work with the major conductors: Claudio Abbado, Riccardo Muti, Daniel Barenboim, Carlo Maria Giulini, Zubin Mehta, Wolfgang Savallisch, Valery Gergev, Myung wun Chung, Georges Prêtre, Giuseppe Sinopoli, Daniele Gatti and Riccardo Chailly."
},
{ id : 66,
  titleProf: "Denis Pascal",
  textProf:"Professor at the CNSMD of Paris.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Denis-Pascal-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :"Denis Pascal performs in France and throughout the world as a soloist and chamber musician. He has made numerous appearances in the United States (Lincoln Center and Merkin Hall in New York, Kennedy Center in Washington, Herbst Theater in San Francisco…) in Asia (Yokohama Festival in Japan, Seoul…) and in Europe (Palermo, Rome, Venice, Lisbon, Helsinki, Liepaja, Madrid, Valencia…). He is regularly invited in Germany to the prestigious Husum Piano Festival, where he performs the most audacious programmes. In France, in Paris, he has been applauded by audiences at the Théâtre des Champs-Élysées, the Théâtre du Châtelet, the Théâtre de la Ville, the Salle Gaveau and the Opéra Garnier, as well as at numerous international festivals.He has performed with the national orchestras of Lyon, Bordeaux, Besançon, Toulouse and the Orchestre d’Auvergne. His concerts are well thought out. Concerned with maintaining a historical awareness of the repertoire, he often leaves the beaten track and gives concerts that are both striking and open to all, rigorously applying a consistent ethic to the Liszt repertoire as well as to impressionist music and post-romantic scores."
},
{ id : 67,
  titleProf: "Chu Yi-Bing",
  textProf:"Former professor at the Beijing Conservatory. He founded the China Philarmonic Cellists and the SuperCello festival.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Chu-Yi-bing-Cello-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle",
  detailProf :" Born into a family of musicians, Yi-Bing Chu began to learn the cello at the age of 8 with his father, who was professor at the Central Conservatory of Music (Beijing, China). At an early age he began to perform, and at 10 recorded his first disc. At that time, the Cultural Revolution was not over and classical music was banned. Then Chu enrolled in the class of the famous cellist Maurice Gendron at the CNSM in Paris, France (Conservatoire National Supérieur de Musique)."
},
{ id : 68,
  titleProf: "Antti Siirala",
  textProf:"Professor at the Hochschule fur Musik und Theater in Munich.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Antti-Siirala-Piano-Masterclass-1.jpg",
  instrumentCategory:"Violoncelle",
  detailProf :" The Finnish pianist Antti Siirala has established himself as one of the finest pianists of his generation. His rich palette of sound colours, his differentiated and songful phrasing and expressive intelligence are praised frequently. Antti Siirala is the winner of numerous international competitions, including the Leeds International Piano Competition. In 1997 he won the International Beethoven Piano Competition Vienna as the youngest laureate in its history. This resulted in the performance of all Beethoven piano works at the Sibelius Academy in Helsinki in the following years and a focus on Beethoven in Siirala’s repertoire. He performs with renowned conductors like Herbert Blomstedt, François-Xavier Roth, Esa-Pekka Salonen and Sakari Oramo, and with orchestras like the Deutsches Symphonie-Orchester Berlin, Bamberger Symphoniker, the Radio Symphony Orchestras of HR, NDR, SWR and WDR, Tonhalle Orchestra Zurich, Wiener Symphoniker, City of Birmingham Symphony, Philharmonia Orchestra London, Residentie Orkest, Gothenburg Symphony, Finnish Radio Symphony, Helsinki Philharmonic Orchestra, San Francisco Symphony and NHK Symphony Orchestra Tokyo."
},
{ id : 69,
  titleProf:"Augustin Dumay",
  textProf:"Professor in Residence at the Chapelle Musicale Reine Elisabeth.",
  imageProf :"https://www.salineacademy.com/wp-content/uploads/2023/06/Augustin-Dumay-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :" Augustin Dumay began his career in 1980 thanks to Herbert von Karajan who invited him to play as a soloist with the Berliner Philharmoniker.Since then, he has gone on to perform with Europe’s best orchestras – Philharmonia, London Symphony, Royal Philharmonic, London Philharmonic, Royal Concertgebouw Amsterdam, Bayerischer Rundfunk, Mahler Chamber, Camerata Salzburg, Tonhalle Zürich – and with the Los Angeles Philharmonic and Montreal Symphony, under the direction of S. Ozawa, C. Davis, C. von Dohnanyi,  C. Dutoit, G. Rozhdestvensky, D. Zinman, Y. Temirkanov, K. Masur, W. Sawallisch, K. Sanderling, I. Fischer, as well as with the leading conductors of a new generation such as D. Harding, A. Gilbert and R. Ticciati.His Duo with pianist Maria João Pires has toured the world several times. His fifty recordings for EMI and Deutsche Grammophon have won multiple international awards. His next CD will be dedicated to Mendelssohn’s Concerto with Orpheus Chamber New York.He plays a 1743 Guarnerius del Gesu, which was the violin of Leonid Kogan."
},
{ id : 70,
  titleProf: "Barnabás Kelemen",
  textProf:"Professor at Budapest’s Liszt Academy and the University of Cologne. Winner of numerous international awards. Member of the Kelemen Quartet and renowned violinist.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Barnabas-Kelemen-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :"Violinist Barnabás Kelemen has conquered the most famous concert halls in the world with his virtuoso technique and dynamic, passionate playing style. Versatile and open-minded, he is an outstanding soloist and chamber musician, as well as an artistic director of festivals and a teacher at renowned institutions. In recent years he has also worked as a conductor.Due to his exceptional sense of style and his comprehensive technical proficiency, Barnabás Kelemen navigates with confidence through the entire catalogue of music written for violin. His repertoire is thus extremely diverse and he performs Early Baroque, Classical, and Romantic works with just as much authenticity as twentieth-century pieces. He is additionally a devoted advocate of contemporary music, with world or Hungarian premieres of works by Kurtág, Ligeti, Schnittke, Gubajdulina, Steve Reich, and Ryan Wigglesworth to his name."
},
{ id : 71,
  titleProf: "Alissa Margulis",
  textProf:"International soloist and professor at Folkwang University, Germany.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Alissa-Margulis-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf :"Appreciated for her expressive and emotional performances, Alissa Margulis regularly plays in important concert halls, such as the Berlin Philharmony, the Carnegie Hall, the Kennedy Center, the Tchaikovsky Hall Moscow, Palacio de Bellas Artes in Mexico City, the Palais des Beaux Arts in Brussels, the Cologne Philharmony, the Vienna Musikverein, Sumida Triphony Hall Tokyo, the Sage Gateshead, the Tonhalle Zurich and the St. Petersburg Philharmonic Hall.Born in Germany into a family of Russian musicians, Alissa Margulis studied in Cologne with Zakhar Bron, in Brussels with Augustin Dumay, and in Vienna with Pavel Vernikov. She won numerous prizes at international violin competitions and was awarded the “Pro Europa” prize of the European Arts Foundation, which was presented to her by Daniel Barenboim in Berlin."
},
{ id : 72,
  titleProf: "Antoine Palloc",
  textProf:"Pianist and singing teacher.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Antoine-Palloc-Voice-Masterclass-1.jpg",
  instrumentCategory: "Piano, voix",
  detailProf :"Originally from Nice, Antoine Palloc studied music with Catherine Collard. After winning First Prize in piano and chamber music, he chose to specialize with a Masters in the Art of Vocal Accompaniment with Dalton Baldwin and Martin Katz. Moreover, Palloc is a dedicated teacher who has regularly led masterclasses and taught in very reputable schools, including: Centre de formation lyrique de l’Opéra Bastille, Université de Tokyo, Opéra de Séoul, Académie internationale d’été de Nice, Université du Michigan, Nagaoka Lyric Hall, Jeunes Voix du Rhin, Tokyo Opéra Studio, Université d’Istanbul, Académie Franz Liszt de Budapest, Pro’scenio, Pôle lyrique d’excellence, Opéra de Monte-Carlo, Pézénas enchanté, and the Fondation des Treilles. He has recorded alongside Jennifer Larmore in a recital of American melodies, “My Native Land” with Warner Classic, and featured in the DVD “Jennifer Larmore Live” (VAI music). In addition, he has recoded many works of mélodies françaises with Decca and Saphir Productions, as well as “Notturno” at Opera Rara Rara, “The Side Show” by Charles Ives for Harmondia Mundi. Alongside Melody Louledjian, he recorded the album “Fleurs” with Aparté. Antoine Palloc is recipient of France’s Chevalier des Arts et des Lettres."
},
{ id : 73,
  titleProf: "Aleksandar Madžar",
  textProf:"Professor at Hochschule für Musik und Theater in Hamburg.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Aleksandar-Madzar-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf:"Aleksandar Madžar was born in Belgrade in 1968. He started playing the piano with Gordana Malinovic at the age of six, and later studied with Arbo Valdma, Elisso Virsaladze, and Daniel Blumenthal in Novi Sad, Belgrade, Moscow, and Brussels. He won prizes at the Geneva, Leeds, Ferrucio Busoni, and Umberto Micheli International Piano competitions, and made his debut with the Berlin Philharmonic and Iván Fischer in 1990. Since then, he has performed regularly throughout Europe, enjoying a rich and varied career giving solo and chamber music recitals, as well as performing concertos with conductors André Previn, Marcello Viotti, Paavo Järvi, and Andris Nelsons. On occasion, he tours North and South America, South Africa, the Far East, and Australia. Aleksandar Madžar is a frequent guest of Wigmore Hall, the Théâtre de la Ville in Paris, the Palais des Beaux-Arts in Brussels, and Het Concertgebouw in Amsterdam. His regular chamber music partners include the Takács Quartet, Anthony Marwood, Vilde Frang and the soprano Juliane Banse. He teaches at the Royal Flemish Conservatoire in Brussels, and at the Hochschule für Musik und Theater in Hamburg."
},
{ id : 74,
  titleProf: "Alexander Chaushian",
  textProf:"Professor at the Royal College of Music of London. He is a laureate prize winner of many international competitions, including International Tchaikovsky Competition.",
  detailProf:" Now regarded as one of the finest cellists of the younger generation, Alexander Chaushian has performed extensively throughout the world as a soloist with orchestras such as the Royal Philharmonic Orchestra, the Philharmonia, the Academy of St Martin-in- the-Fields, The London Mozart Players, The Vienna Chamber Orchestra, Orchestre de la Suisse Romande, The Boston Pops and The Armenian",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Alexander-Chaushian-Cello-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle",
},
{ id : 75,
  titleProf: "Martin Beaver",
  textProf:"Professor of Violin and Chamber Music at the Colburn Conservatory of Music and Colburn Music Academy in Los Angeles. 1st violin of the legendary Tokyo string quartet.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Martin-Beaver-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
  detailProf : "As a member of the Tokyo String Quartet, Martin Beaver was privileged to perform on the 1727 Stradivarius violin from the “Paganini Quartet” set of instruments, on generous loan to the quartet from the Nippon Music Foundation.Recordings of the Tokyo String Quartet during his tenure notably include the complete Beethoven quartets on the Harmonia Mundi label. Mr. Beaver’s concerto and recital appearances span four continents with orchestras such as the San Francisco Symphony, the Toronto Symphony, l’Orchestre Philharmonique de Liège and the Sapporo Symphony Orchestra and under the batons of Kazuyoshi Akiyama, Raymond Leppard, Gilbert Varga and Yannick Nézet-Séguin among others."
},
{ id : 76,
  titleProf: "Olivier Gardon",
  textProf:"Professor at the Hochschule in Hanover, at the Schola Cantorum in Paris. He was the artistic director of the International Summer Academy in Nice.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Philippe-Bernold-Flute-Masterclass-1.jpg",
  instrumentCategory: "Piano",
  detailProf :"Olivier Gardon has taught in prestigious establishments: Hochschule HMTMH Hannover, MozarteumSommerakademie Salzburg, Conservatoire de Paris (CRR). Currently Olivier Gardon teaches at the Schola Cantorum in Paris, Many universities and Hochschule around the world have invitedhim to give masterclasses: Toho Gakuen Tokyo, Yonsei University Seoul, Bowdoin University (Maine), Royal Conservatory of Brussels, Trinity college of Music Laban (London) Leipzig, Lübeck. Olivier Gardon’s discography includes works by Beethoven, Brahms, Bizet, Debussy, Liszt, Mussorgsky, Milhaud, Schumann, complete piano works by Louis Vierne and complete chamber music by Alkanwith Kang Dong Suk and Yvan Chiffoleau (Prix Spécial de la Nouvelle Académie du disque français).In 2011, Bärenreiter publishes the new Urtext Edition of Vierne’s piano Préludes and Nocturnes revised by Mr. Gardon."
}];